apiVersion: v1
kind: Service
metadata:
 name: <APPLICATION_NAME>
spec:
 ports:
 - port: 3005
   targetPort: 3002
   protocol: TCP
   name: http
 selector:
   app: <APPLICATION_NAME>
 type: LoadBalancer
 loadBalancerIP: <RESERVED_STATIC_IP>