apiVersion: v1
kind: Service
metadata:
  name: <SERVICE_NAME>
  namespace: <NAMESPACE(0)>
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: <APPLICATION_NAME>
spec:
  type: LoadBalancer
  selector:
    app: <APPLICATION_NAME>
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP