apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: my-nodejs-application
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: my-nodejs-application
   spec:
     containers:
     - name: my-nodejs-application
       image: gcr.io/GOOGLE_PROJECT_ID/nodejs:v54	
       ports:
         - containerPort: 3002