apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: my-nodejs-application-DOCKER_IMAGE_TAG
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: my-nodejs-application-DOCKER_IMAGE_TAG
   spec:
     containers:
     - name: my-nodejs-application
       image: gcr.io/GOOGLE_PROJECT_ID/DOCKER_IMAGE_NAME
       ports:
         - containerPort: 3002