apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-nodejs-application-hpa
  namespace: default
spec:
    maxReplicas: 6
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: my-nodejs-application-DOCKER_IMAGE_TAG
    metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80